name: Node - PR Close Time
on:
  pull_request:
    types: [ closed ]
jobs:
  node_timer:
    runs-on: ubuntu-latest
    name: Test the action on pr close
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Action
        uses: 13thThief/test-project@main
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Run node
        run: npm install
